run:
  timeout: 30m
  build-tags:
    - testing

linters:
  disable-all: true
  enable: # please keep this alphabetized
    - errcheck
    - gocritic
    - gocyclo
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
