[workspace]
# See https://github.com/rust-lang/rfcs/blob/master/text/2957-cargo-features2.md
# Without resolver = 2, using `cargo build --features x` to build `cmd`
# will _not_ propagate the feature `x` into `cmd`'s direct dependencies.
resolver = "2"
members = [
    "components/codec",
    "components/model",
    "components/transport",
    "components/service",
    "components/store",
    "data-node",
    "front-end-sdk"
]

[workspace.dependencies]
async-channel = { version = "1.8" }
byteorder = "1"
bytes = "1"
core_affinity = "0.7"
crc = "3.0"
futures = { version = "0.3" }
monoio = { version = "0.0", features = ["splice"] }
monoio-macros = "0.0"
num_cpus = "1"
thiserror = "1.0"
crossbeam = "0.8"
clap = { version = "4.0", features = ["derive"] }
num_enum = "0.5"
dashmap = "5.4"
seahash = "4.1"

flatbuffers = "22.10"

# Raft
raft = "0.6"

# Logging
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_warn"] }
slog-async = "2.7"
slog-term = "2.9"

# RocksDB
# rocksdb = { version = "0.19", default-features = false, features = ["lz4"] }

pprof = { version = "0.11", features = ["flamegraph"] }


rand = { version = "0.8" }
uuid = { version = "1.2", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] }