[workspace]
# See https://github.com/rust-lang/rfcs/blob/master/text/2957-cargo-features2.md
# Without resolver = 2, using `cargo build --features x` to build `cmd`
# will _not_ propagate the feature `x` into `cmd`'s direct dependencies.
resolver = "2"
members = [
    "components/codec",
    "components/model",
    "components/protocol",
    "components/placement-client",
    "components/transport",
    "components/service",
    "components/store",
    "components/util",
    "data-node",
    "front-end-sdk"
]

[workspace.dependencies]

# Communicate among tasks of the same thread
local-sync = { version = "0.0" }

# Communicate among multiple threads
async-channel = { version = "1.8" }

byteorder = "1"
bytes = "1"
core_affinity = "0.8"
crc = "3.0"
futures = { version = "0.3" }
pin-project = { version = "1" }
io-uring = "0.5"
tokio-uring = "0.4"
tokio = { version = "1", features = ["full"] }
crossbeam = "0.8"
monoio = { git = "https://github.com/lizhanhui/monoio.git", features = ["splice"], branch = "config_uring" }
monoio-macros = "0.0"
num_cpus = "1"
thiserror = "1.0"
clap = { version = "4.0", features = ["derive"] }
num_enum = "0.5"

flatbuffers = { git = "https://github.com/google/flatbuffers.git", tag = "v23.1.4" }

libc = "0.2"
nix = "0.26"
prometheus = "0.13"

# Logging
slog = { version = "2.7", features = ["max_level_debug", "release_max_level_warn"] }
slog-async = "2.7"
slog-term = "2.9"

# RocksDB
# rocksdb = { version = "0.19", default-features = false, features = ["lz4"] }

pprof = { version = "0.11", features = ["flamegraph"] }


rand = { version = "0.8" }
uuid = { version = "1.2", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] }
mockall = "0.11"
cargo-llvm-cov = "0.5"

flatc-rust = { version = "0.2" }

gethostname = "0.4"

ordinal = "0.3"