[build]
pre-build = [
    "apt-get update && apt-get install --assume-yes --no-install-recommends libclang-dev clang", # required by rocksdb
]

[build.env]
passthrough = [
    "SKIP_FLATC=1",
    "ROCKSDB_COMPILE=1", # compile rocksdb from source
]
