# PM Configuration.

# urls for peer traffic
peerUrls: "http://127.0.0.1:2380"
# urls for client traffic
clientUrls: "http://127.0.0.1:2379"
# advertise urls for peer traffic
advertisePeerUrls: "http://127.0.0.1:2380"
# advertise urls for client traffic
advertiseClientUrls: "http://127.0.0.1:2379"

# human-readable name for this PM member
name: "pm-hostname"
# path to the data directory
dataDir: "default.pm-hostname"
# the initial cluster configuration for bootstrapping
initialCluster: "pm=http://127.0.0.1:2380"
# expiration time of the leader, in seconds
leaderLease: 3
# time interval for checking the leader's priority
leaderPriorityCheckInterval: 60000000000 # 1 minute

etcd:
  # set different tokens to prevent communication between PMs in different clusters
  initialClusterToken: "pm-cluster"
