[package]
name = "data-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
bytes = "1"
core_affinity = "0.7"
crc = "3.0"
monoio = "0.0"
num_cpus = "1"
thiserror = "1.0"
crossbeam = "0.8"
clap = { version = "4.0", features = ["derive"] }
num_enum = "0.5"
dashmap = "5.4"
seahash = "4.1"

# Logging
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_warn"] }
slog-async = "2.7"
slog-term = "2.9"
