[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
monoio = { workspace = true }
monoio-macros = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
slog =  { workspace = true }
local-sync = { workspace = true }
nix = { workspace = true }
prometheus = { workspace = true }

[dev-dependencies]
slog-async =  { workspace = true }
slog-term =  { workspace = true }