[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
tokio-uring = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
slog =  { workspace = true }
nix = { workspace = true }
prometheus = { workspace = true }
pin-project = { workspace = true }
libc = { workspace = true }
io-uring = { workspace = true }
crossbeam = { workspace = true }
core_affinity = { workspace = true }
tokio = { workspace = true }
util = { path = "../util" }

[dev-dependencies]
slog-async =  { workspace = true }
slog-term =  { workspace = true }
cargo-llvm-cov = { workspace = true }
uuid = { workspace = true }