apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: placement-manager
spec:
  containers:
    - image: alpine:3.16
      command:
        - /bin/sh
        - "-c"
        - "sleep 10m"
      imagePullPolicy: IfNotPresent
      name: alpine
  restartPolicy: Always
