name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [ "master", "develop" ]

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: 'true'
  paths-filter:
    runs-on: ubuntu-latest
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    outputs:
      java: ${{ steps.filter.outputs.java }}
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            java:
              - 'sdks/java/**'
            rust:
              - 'data-node/**'
              - 'components/**'
              - 'sdks/rust/**'
  java-build:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.java == 'true' }}
    uses: ./.github/workflows/java_build.yml
  rust-build:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.rust == 'true' }}
    uses: ./.github/workflows/rust_build.yml
  build-result:
    runs-on: ubuntu-latest
    needs: [java-build, rust-build]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: Collect build result
        run: |
          if echo java-${{ needs.java-build.result }},rust-${{ needs.rust-build.result }} | grep -E 'cancelled|failure' -o > null
          then
            echo "There are failed/cancelled builds"
            exit 1 
          else
            echo "All builds are successful/skipped"
            exit 0
          fi
