name: CI - Run tests

on: workflow_call
permissions: read-all

jobs:
  test:
    strategy:
      matrix:
        go-version: [ "1.19" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Go Cache
      uses: actions/cache@v3
      with:
        path: .go/cache
        key: ${{matrix.platform}}-${{matrix.go-version}}-go-test-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{matrix.platform}}-${{matrix.go-version}}-go-test-
          ${{matrix.platform}}-${{matrix.go-version}}-go-
    - name: Test
      run: make test GOFLAGS="-v" GO_VERSION=${{ matrix.go-version }} GO_TEST_FLAGS="-coverprofile=covprofile -covermode=atomic -coverpkg=./..."
    - name: Send coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./covprofile
        fail_ci_if_error: true
        verbose: true
