name: Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo Crates
      uses: actions/cache@v3
      with: 
        path: |
          ~/.cargo
          ~/.rustup
        key: ${{ runner.os }}-cargo
    - name: Install Flatbuffers
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget -O flatc.zip https://github.com/google/flatbuffers/releases/download/v23.1.4/Linux.flatc.binary.g++-10.zip
        unzip flatc.zip
        sudo mv flatc /usr/local/bin/
        rm flatc.zip
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
