name: Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env: 
      CARGO_HOME: ~/.cargo
      RUSTUP_HOME: ~/.rustup
    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo Crates
      uses: actions/cache@v3
      with: 
        path: |
          ~/.cargo
          ~/.rustup
          /usr/local/bin/flatc
        key: ${{ runner.os }}-cargo
    - name: Install Deps
      run: |
        ./scripts/install_deps.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
