name: Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Flatbuffers
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        if [ "$RUNNER_OS" == "Linux" ]; then
          wget -O flatc.zip https://github.com/google/flatbuffers/releases/download/v23.1.4/Linux.flatc.binary.g++-10.zip
        elif [ "$RUNNER_OS" == "macOS" ]; then
          wget -O flatc.zip https://github.com/google/flatbuffers/releases/download/v23.1.4/MacIntel.flatc.binary.zip
        fi
        unzip flatc.zip
        sudo mv flatc /usr/bin/
        rm flatc.zip
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
