name: Data Node Release

on:
  push:
    tags:
      - 'data-node-v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install Deps
        run: |
          ./scripts/install_deps.sh
      - name: Build
        working-directory: ./dist
        run: |
          cargo build --release
          ../scripts/package_deb.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: ./dist/data-node.deb
