# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.
name: Publish snapshot package to the Maven Central Repository
on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-22.04
    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      CI_TEST: ${{ secrets.ONLY_FOR_TEST }}
      ENV_SHOW: "show me"
    steps:
      - name: test env
        env:
          NEW_CI_TEST: ${{ secrets.ONLY_FOR_TEST }}
        run: |
          echo "2 new test: $NEW_CI_TEST, $ENV_SHOW, ${{ secrets.ONLY_FOR_TEST }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          ./scripts/install_deps.sh
      - name: Generate flatbuffers java classes
        run: |
          flatc --version
          flatc --java -o 'sdks/java/flatc/src/main/java' --java-package-prefix 'com.automq.sdk.elastic.stream.flatc' --gen-object-api components/protocol/fbs/rpc.fbs components/protocol/fbs/model.fbs
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "gradle"
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }} # env variable for GPG private key passphrase
      - name: Publish snapshot package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          gradle-version: wrapper
          build-root-directory: ./sdks/java
