name: Run lint

on: [ push, pull_request ]

jobs:
  lint:
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Go Cache
      uses: actions/cache@v3
      with:
        path: .go/cache
        key: ${{matrix.platform}}-${{matrix.go-version}}-go-lint
    - name: Lint
      run: make lint
