name: Nightly Build
on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  pm:
    name: Placement Manager
    strategy:
      matrix:
        go-version: [ "1.20" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./placement-manager/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pm-nightly-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pm-nightly-
            ${{matrix.platform}}-${{matrix.go-version}}-pm-
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: elasticstream
          password: ${{ secrets.DOCKERHUB_CI_TOKEN }}
      - name: Build and Push Images
        run: make manifest-list GO_VERSION=${{ matrix.go-version }} VERSION=nightly ALL_PLATFORMS=linux/amd64
