name: Placement Manager - CI

on:
  workflow_call:
permissions: read-all

defaults:
  run:
    working-directory: ./placement-manager

jobs:
  flatc:
    name: Verify Flatbuffers
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Flatbuffers
        run: |
          wget -O flatc.zip https://github.com/google/flatbuffers/releases/download/v23.3.3/Linux.flatc.binary.g++-10.zip
          unzip flatc.zip
          sudo mv flatc /usr/local/bin
          rm flatc.zip
          flatc --version
      - name: Verify Flatbuffers
        run: |
          make flatc
          git diff --exit-code
  lint:
    name: Lint
    strategy:
      matrix:
        go-version: [ "1.20" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./placement-manager/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pm-lint-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pm-lint-
            ${{matrix.platform}}-${{matrix.go-version}}-pm-
      - name: Lint
        run: make lint GO_VERSION=${{ matrix.go-version }}
  crossbuild:
    name: Cross Build
    strategy:
      matrix:
        go-version: [ "1.19", "1.20" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./placement-manager/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pm-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pm-build-
            ${{matrix.platform}}-${{matrix.go-version}}-pm-
      - name: Build containers
        run: make all-container GO_VERSION=${{ matrix.go-version }}
  test:
    name: Test
    strategy:
      matrix:
        go-version: [ "1.19", "1.20" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./placement-manager/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pm-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pm-test-
            ${{matrix.platform}}-${{matrix.go-version}}-pm-
      - name: Test
        run: make test GOFLAGS="-v" GO_VERSION=${{ matrix.go-version }} GO_TEST_FLAGS="-coverprofile=covprofile -covermode=atomic -coverpkg=./..."
