name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  dn-deb:
    name: Build Data Node Debian Packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.4.0
        with:
          prefix-key: ""
          env-vars: ""
      - name: Install Deps
        run: |
          ./scripts/install_deps.sh
      - name: Build
        working-directory: ./dist
        run: |
          cargo build --release
          ../scripts/package_deb.sh
  pm-deb:
    name: Build Placement Manager Debian Packages
    strategy:
      matrix:
        go-version: [ "1.20" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: ./placement-manager
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./placement-manager/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pm-release-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pm-release-
            ${{matrix.platform}}-${{matrix.go-version}}-pm-
      - name: Build Debian Packages
        run: make all-deb GO_VERSION=${{ matrix.go-version }}
  publish:
    runs-on: ubuntu-latest
    needs: [dn-deb, pm-deb]
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ./dist/data-node.deb
            ./placement-manager/distribution/*.deb
