name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  pm-images:
    name: Build and Push Placement Manager Images
    strategy:
      matrix:
        go-version: [ "1.20" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./placement-manager/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pm-release-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pm-release-
            ${{matrix.platform}}-${{matrix.go-version}}-pm-
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: elasticstream
          password: ${{ secrets.DOCKERHUB_READ_WRITE_TOKEN }}
      - name: Build and Push Release Images
        run: make manifest-list GO_VERSION=${{ matrix.go-version }}
